/* global React */
// ─── Mímir fixtures ───────────────────────────────────────────────
// Multiple mounts (instances), pages with frontmatter + zones,
// ravns bound to each mount, ingest sources, lint issues, routing.

// ─── Mounts (instances we can connect to) ─────────────────────────

const MOUNTS = [
  {
    name: 'local',
    role: 'local',
    host: 'local.mimir',
    url: 'file:///home/olaf/.ravn/mimir',
    priority: 0,
    categories: null,          // accepts all
    status: 'healthy',
    pages: 214,
    sources: 186,
    lint_issues: 7,
    last_write: '2 min ago',
    embedding: 'all-MiniLM-L6-v2',
    size_kb: 4820,
    desc: "The operator's own notebook. Always writable, first in read order.",
  },
  {
    name: 'shared',
    role: 'shared',
    host: 'mimir.odin.niuu.world',
    url: 'https://mimir.odin.niuu.world',
    priority: 1,
    categories: null,
    status: 'healthy',
    pages: 1472,
    sources: 904,
    lint_issues: 24,
    last_write: '11 min ago',
    embedding: 'all-mpnet-base-v2',
    size_kb: 38104,
    desc: 'The realm-wide pool. Every ravn in Asgard reads from here.',
  },
  {
    name: 'kanuck',
    role: 'domain',
    host: 'mimir.kanuck.niuu.world',
    url: 'https://mimir.kanuck.niuu.world',
    priority: 2,
    categories: ['household/', 'kanuck/'],
    status: 'healthy',
    pages: 338,
    sources: 221,
    lint_issues: 3,
    last_write: '1 hr ago',
    embedding: 'all-MiniLM-L6-v2',
    size_kb: 7210,
    desc: 'Household-scoped. Family calendars, recipes, home-infra runbooks.',
  },
  {
    name: 'forge',
    role: 'domain',
    host: 'mimir.forge.niuu.world',
    url: 'https://mimir.forge.niuu.world',
    priority: 3,
    categories: ['technical/forge/'],
    status: 'degraded',
    pages: 94,
    sources: 62,
    lint_issues: 12,
    last_write: '3 hr ago',
    embedding: 'all-MiniLM-L6-v2',
    size_kb: 1820,
    desc: 'Physical-fabrication domain — 3D printing, CNC, resin profiles.',
  },
];

// ─── Write routing (mirrors WriteRouting config) ─────────────────

const ROUTING_RULES = [
  { prefix: 'self/',              mounts: ['local'] },
  { prefix: 'household/',         mounts: ['shared', 'kanuck'] },
  { prefix: 'kanuck/',            mounts: ['kanuck'] },
  { prefix: 'technical/forge/',   mounts: ['forge', 'shared'] },
  { prefix: 'technical/',         mounts: ['local', 'shared'] },
  { prefix: 'projects/',          mounts: ['local', 'shared'] },
  { prefix: 'entities/',          mounts: ['shared'] },
];
const ROUTING_DEFAULT = ['local'];

// ─── Ravns bound to mímirs ────────────────────────────────────────
// Each ravn has a persona, allowed tools, and a set of mounts it
// reads from / writes to (ravn-side composite).

const RAVNS = [
  {
    id: 'fjolnir',
    name: 'Fjölnir',
    rune: 'ᚱ',
    persona: 'mimir-curator',
    role: 'Knowledge curator',
    state: 'thinking',
    tools: ['mimir','web','file','ravn'],
    bindings: [
      { mount: 'local',  mode: 'rw' },
      { mount: 'shared', mode: 'rw' },
    ],
    expertise: ['entities/people', 'entities/orgs', 'projects/niuu'],
    pages_touched: 482,
    last_dream: '8 hr ago',
    dream_last: { pages_updated: 12, entities_created: 3, lint_fixes: 6 },
    bio: "Synthesises raw sources into compiled-truth pages. Runs the nightly dream cycle across the local + shared mounts. Prefers restatement over transcription; refuses to copy-paste source text.",
  },
  {
    id: 'saga',
    name: 'Saga',
    rune: 'ᚱ',
    persona: 'mimir-archivist',
    role: 'Timeline keeper',
    state: 'observing',
    tools: ['mimir','web'],
    bindings: [
      { mount: 'local',  mode: 'r'  },
      { mount: 'shared', mode: 'w'  },
    ],
    expertise: ['timeline', 'sources/web', 'log'],
    pages_touched: 1104,
    last_dream: '1 day ago',
    dream_last: { pages_updated: 0, entities_created: 0, lint_fixes: 2 },
    bio: "Records history. Appends timeline entries and never rewrites them. Reads the local mount for context, writes the shared mount so every warden inherits the record.",
  },
  {
    id: 'sindri',
    name: 'Sindri',
    rune: 'ᚱ',
    persona: 'forge-operator',
    role: 'Fabrication ops',
    state: 'working',
    tools: ['mimir','terminal','file'],
    bindings: [
      { mount: 'forge',  mode: 'rw' },
      { mount: 'local',  mode: 'r'  },
    ],
    expertise: ['technical/forge/resin', 'technical/forge/cnc'],
    pages_touched: 78,
    last_dream: '3 hr ago',
    dream_last: { pages_updated: 4, entities_created: 1, lint_fixes: 0 },
    bio: "Maintains the forge domain mímir. Updates resin exposure profiles after each print run, cross-references failures, keeps G-code templates current.",
  },
  {
    id: 'eir',
    name: 'Eir',
    rune: 'ᚱ',
    persona: 'household-steward',
    role: 'Household steward',
    state: 'idle',
    tools: ['mimir','web','file'],
    bindings: [
      { mount: 'kanuck', mode: 'rw' },
      { mount: 'shared', mode: 'r'  },
    ],
    expertise: ['household/recipes', 'household/calendar', 'kanuck/infra'],
    pages_touched: 211,
    last_dream: '6 hr ago',
    dream_last: { pages_updated: 2, entities_created: 0, lint_fixes: 1 },
    bio: "Keeps the household mímir honest — recipes annotated with real outcomes, calendar entries reconciled against actual events.",
  },
  {
    id: 'vor',
    name: 'Vör',
    rune: 'ᚱ',
    persona: 'source-linter',
    role: 'Lint sweeper',
    state: 'observing',
    tools: ['mimir'],
    bindings: [
      { mount: 'local',  mode: 'rw' },
      { mount: 'shared', mode: 'rw' },
      { mount: 'kanuck', mode: 'rw' },
      { mount: 'forge',  mode: 'rw' },
    ],
    expertise: ['lint', 'wikilinks', 'frontmatter'],
    pages_touched: 2118,
    last_dream: '30 min ago',
    dream_last: { pages_updated: 0, entities_created: 0, lint_fixes: 18 },
    bio: "Runs lint on every mount during idle cycles. Auto-fixes L05 (broken wikilinks cleanup), L11 (stale index), L12 (invalid frontmatter). Escalates L02 contradictions to Fjölnir.",
  },
  {
    id: 'ratatoskr',
    name: 'Ratatoskr',
    rune: 'ᚱ',
    persona: 'ingest-scout',
    role: 'Ingest scout',
    state: 'working',
    tools: ['mimir','web'],
    bindings: [
      { mount: 'local',  mode: 'w' },
      { mount: 'shared', mode: 'w' },
    ],
    expertise: ['sources/web', 'sources/rss', 'sources/arxiv'],
    pages_touched: 304,
    last_dream: '2 hr ago',
    dream_last: { pages_updated: 0, entities_created: 9, lint_fixes: 0 },
    bio: "Watches feeds, ingests new sources, tags them with provisional categories. Never synthesises — hands off to Fjölnir.",
  },
];

// ─── Pages (selected set, varied across categories + mounts) ──────

const PAGES = [
  {
    path: 'entities/person-karpathy.md',
    title: 'Andrej Karpathy',
    type: 'entity',
    confidence: 'high',
    entity_type: 'person',
    category: 'entities',
    summary: 'AI researcher, advocate for small focused LMs and minimal architectures.',
    mounts: ['local','shared'],
    updated_at: '2026-04-17 14:22',
    updated_by: 'fjolnir',
    source_ids: ['src_abc123','src_def456','src_9a7c22'],
    related: ['project-niuu','concept-compounding-knowledge','concept-minimal-llm'],
    size: 3420,
    content: {
      keyFacts: [
        'AI researcher. Former Tesla AI director. Founding member at OpenAI.',
        'Advocates for small, focused language models over monolithic generalists.',
        'Publishes high-signal walkthroughs of model internals — micrograd, nanoGPT, llm.c.',
      ],
      relationships: [
        { slug: 'project-niuu', note: 'referenced as inspiration for the compounding-knowledge design' },
        { slug: 'concept-minimal-llm', note: 'central advocate; most-cited source on our compiled-truth page' },
      ],
      assessment: "High-signal follow. Output is consistently practical. Cite when defending a 'smaller model, better data' decision — but don't treat position statements as universally endorsed.",
      timeline: [
        { date: '2026-03-10', note: 'Shared post on X about minimal LLM architectures.', source: '@karpathy, X/Twitter, 2026-03-10' },
        { date: '2026-04-01', note: 'Published blog post on memory systems.',            source: 'karpathy.github.io, web, 2026-04-01' },
        { date: '2026-04-14', note: 'Referenced Niuu compounding-knowledge design in reply thread.', source: '@karpathy, X/Twitter, 2026-04-14' },
      ],
    },
  },
  {
    path: 'projects/niuu/architecture.md',
    title: 'Niuu architecture',
    type: 'topic',
    confidence: 'high',
    category: 'projects',
    summary: 'Ports-and-adapters backbone. Sleipnir fans events; Bifröst gates inference; ravens run against their bindings.',
    mounts: ['local','shared'],
    updated_at: '2026-04-18 09:04',
    updated_by: 'fjolnir',
    source_ids: ['src_01fa22','src_81bb07'],
    related: ['project-niuu','concept-hexagonal','component-sleipnir'],
    size: 6140,
  },
  {
    path: 'projects/niuu/agents/raven.md',
    title: 'Raven agent runtime',
    type: 'topic',
    confidence: 'high',
    category: 'projects',
    summary: 'Drive loop, tool registry, composite mímir binding, dream-cycle trigger.',
    mounts: ['local','shared'],
    updated_at: '2026-04-17 20:13',
    updated_by: 'fjolnir',
    source_ids: ['src_4092ab'],
    related: ['project-niuu','concept-drive-loop'],
    size: 4120,
  },
  {
    path: 'technical/forge/resin-profiles.md',
    title: 'Resin exposure profiles',
    type: 'directive',
    confidence: 'medium',
    category: 'technical',
    summary: 'Working profiles for ABS-like, water-washable, and tough resins on the Sparkmaker.',
    mounts: ['forge'],
    updated_at: '2026-04-18 06:40',
    updated_by: 'sindri',
    source_ids: ['src_f01c22'],
    related: ['technology-resin-sla'],
    size: 2180,
  },
  {
    path: 'household/recipes/sourdough.md',
    title: 'Sourdough loaf',
    type: 'preference',
    confidence: 'high',
    category: 'household',
    summary: 'Overnight bulk, 78% hydration, 20-min bench rest, then cold retard.',
    mounts: ['kanuck'],
    updated_at: '2026-04-16 22:18',
    updated_by: 'eir',
    source_ids: ['src_aa11bb'],
    related: [],
    size: 1620,
  },
  {
    path: 'concepts/compounding-knowledge.md',
    title: 'Compounding knowledge',
    type: 'decision',
    confidence: 'high',
    category: 'concepts',
    summary: 'Two-zone page format: compiled truth vs append-only timeline.',
    mounts: ['local','shared'],
    updated_at: '2026-04-12 11:30',
    updated_by: 'fjolnir',
    source_ids: ['src_01fa22'],
    related: ['project-niuu','person-karpathy'],
    size: 2980,
  },
  {
    path: 'self/workflow.md',
    title: 'Daily working pattern',
    type: 'preference',
    confidence: 'medium',
    category: 'self',
    summary: 'Morning deep-work on Niuu backend; afternoon ops & ravn review.',
    mounts: ['local'],
    updated_at: '2026-04-18 08:00',
    updated_by: 'fjolnir',
    source_ids: [],
    related: [],
    size: 640,
  },
  {
    path: 'self/open-questions.md',
    title: 'Open questions',
    type: 'observation',
    confidence: 'low',
    category: 'self',
    summary: 'Running list — things to resolve, flagged for re-synthesis.',
    mounts: ['local'],
    updated_at: '2026-04-17 23:55',
    updated_by: 'fjolnir',
    source_ids: [],
    related: [],
    size: 880,
    flagged: true,
  },
  {
    path: 'entities/project-niuu.md',
    title: 'Project Niuu',
    type: 'entity',
    entity_type: 'project',
    confidence: 'high',
    category: 'entities',
    summary: 'Homegrown agentic-infra platform — hex-arch, Norse naming.',
    mounts: ['shared','local'],
    updated_at: '2026-04-17 15:12',
    updated_by: 'fjolnir',
    source_ids: ['src_01fa22','src_81bb07','src_9a7c22'],
    related: ['person-karpathy','concept-compounding-knowledge'],
    size: 5210,
  },
  {
    path: 'technical/kubernetes/cluster-upgrade.md',
    title: 'Cluster upgrade runbook',
    type: 'directive',
    confidence: 'high',
    category: 'technical',
    summary: 'valhalla / valaskjalf upgrade path with rollback.',
    mounts: ['local','shared'],
    updated_at: '2026-04-10 11:15',
    updated_by: 'fjolnir',
    source_ids: ['src_6677aa'],
    related: ['technology-k8s','component-valhalla'],
    size: 4480,
  },
  {
    path: 'entities/concept-drive-loop.md',
    title: 'Drive loop',
    type: 'entity',
    entity_type: 'concept',
    confidence: 'medium',
    category: 'entities',
    summary: 'Per-ravn scheduling loop — observe, decide, act, write.',
    mounts: ['shared'],
    updated_at: '2026-04-14 17:21',
    updated_by: 'fjolnir',
    source_ids: ['src_4092ab'],
    related: ['project-niuu','component-ravn'],
    size: 1920,
  },
  {
    path: 'kanuck/infra/homelab.md',
    title: 'Kanuck homelab inventory',
    type: 'observation',
    confidence: 'high',
    category: 'kanuck',
    summary: '2× DGX Spark, 4× Mac mini, 3× EPYC box, UniFi topology.',
    mounts: ['kanuck'],
    updated_at: '2026-04-15 09:30',
    updated_by: 'eir',
    source_ids: ['src_c09ee1'],
    related: [],
    size: 3120,
  },
  {
    path: 'technical/forge/cnc-feeds.md',
    title: 'CNC feeds & speeds — aluminium',
    type: 'directive',
    confidence: 'low',
    category: 'technical',
    summary: 'Working feeds for 6061 on the Shapeoko Pro.',
    mounts: ['forge'],
    updated_at: '2026-04-08 12:45',
    updated_by: 'sindri',
    source_ids: [],
    related: [],
    size: 1080,
    flagged: true,
  },
  {
    path: 'log.md',
    title: 'Activity log',
    type: 'observation',
    confidence: 'high',
    category: 'meta',
    summary: 'Append-only ingest / write / lint record.',
    mounts: ['local','shared','kanuck','forge'],
    updated_at: '2026-04-18 10:14',
    updated_by: 'system',
    source_ids: [],
    related: [],
    size: 18420,
  },
  {
    path: 'index.md',
    title: 'Content catalog',
    type: 'topic',
    confidence: 'high',
    category: 'meta',
    summary: 'Auto-generated page directory.',
    mounts: ['local','shared','kanuck','forge'],
    updated_at: '2026-04-18 10:12',
    updated_by: 'system',
    source_ids: [],
    related: [],
    size: 9140,
  },
];

// ─── Lint issues (L01–L12) ───────────────────────────────────────

const LINT_CHECKS = {
  L01: { name: 'Orphans',              severity: 'info',    autofix: false, desc: 'Page not linked in index.md' },
  L02: { name: 'Contradictions',       severity: 'warning', autofix: false, desc: '[CONTRADICTION] marker present in body' },
  L03: { name: 'Stale sources',        severity: 'info',    autofix: false, desc: 'Source re-fetch required' },
  L04: { name: 'Broken wikilinks',     severity: 'warning', autofix: false, desc: '[[slug]] target missing' },
  L05: { name: 'Missing source attr.', severity: 'warning', autofix: true,  desc: 'Timeline entry lacks [Source: …]' },
  L06: { name: 'Thin pages',           severity: 'info',    autofix: false, desc: 'Body < 120 chars' },
  L07: { name: 'Stale content',        severity: 'info',    autofix: false, desc: 'Updated > 60 days ago' },
  L08: { name: 'Stale source fetch',   severity: 'info',    autofix: false, desc: 'Triggered by web re-fetch' },
  L09: { name: 'Timeline edited',      severity: 'error',   autofix: false, desc: 'Timeline entry was modified, not appended' },
  L10: { name: 'Missing frontmatter',  severity: 'warning', autofix: false, desc: 'YAML frontmatter block absent' },
  L11: { name: 'Stale index',          severity: 'warning', autofix: true,  desc: 'index.md out of sync' },
  L12: { name: 'Invalid frontmatter',  severity: 'warning', autofix: true,  desc: "Missing required 'type' field" },
};

const LINT_ISSUES = [
  { id:'L09', page:'entities/person-karpathy.md', mount:'local',  msg:'Timeline entry for 2026-04-01 was edited after write.' },
  { id:'L04', page:'technical/forge/cnc-feeds.md', mount:'forge',  msg:'Wikilink [[technology-aluminium-6061]] target missing.' },
  { id:'L05', page:'self/open-questions.md',      mount:'local',  msg:'Timeline entry 2026-04-10 missing [Source:] attribution.' },
  { id:'L02', page:'projects/niuu/agents/raven.md', mount:'shared', msg:'[CONTRADICTION] present — drive loop cadence (250ms vs 400ms).' },
  { id:'L01', page:'technical/forge/resin-profiles.md', mount:'forge', msg:'Page not linked in index.md.' },
  { id:'L12', page:'kanuck/infra/homelab.md',     mount:'kanuck', msg:"Frontmatter missing 'type' field." },
  { id:'L06', page:'self/workflow.md',            mount:'local',  msg:'Body is 640 chars — below thin-page threshold.' },
  { id:'L07', page:'technical/kubernetes/cluster-upgrade.md', mount:'shared', msg:'Updated 8 days ago; source last fetched 61 days ago.' },
  { id:'L11', page:'index.md',                    mount:'kanuck', msg:'index.md missing 2 pages present on disk.' },
  { id:'L04', page:'entities/concept-drive-loop.md', mount:'shared', msg:'Wikilink [[component-ravn]] target missing.' },
  { id:'L01', page:'concepts/compounding-knowledge.md', mount:'local', msg:'Not linked in index.md.' },
  { id:'L05', page:'technical/forge/resin-profiles.md', mount:'forge', msg:'Timeline entry 2026-04-10 missing [Source:] attribution.' },
];

// ─── Recent sources + events ─────────────────────────────────────

const SOURCES = [
  { id:'src_9a7c22', title:"Karpathy blog — 'Memory systems'", type:'web',      origin:'karpathy.github.io', ingested:'2026-04-17 13:44', ravn:'ratatoskr', pages:['entities/person-karpathy.md'], mount:'local' },
  { id:'src_01fa22', title:'Niuu SDD §4 — topology',          type:'document', origin:'niuu/docs/sdd.md',    ingested:'2026-04-17 11:02', ravn:'ratatoskr', pages:['projects/niuu/architecture.md','concepts/compounding-knowledge.md','entities/project-niuu.md'], mount:'local' },
  { id:'src_81bb07', title:'HN discussion — agentic infra',   type:'web',      origin:'news.ycombinator.com',ingested:'2026-04-17 09:12', ravn:'ratatoskr', pages:['entities/project-niuu.md','projects/niuu/architecture.md'], mount:'shared' },
  { id:'src_f01c22', title:'Anycubic resin datasheet — ABS-like tough', type:'document', origin:'anycubic.com/datasheets', ingested:'2026-04-18 06:20', ravn:'sindri', pages:['technical/forge/resin-profiles.md'], mount:'forge' },
  { id:'src_aa11bb', title:'My 78%-hydration notes',          type:'document', origin:'notes/sourdough.txt', ingested:'2026-04-16 21:55', ravn:'eir',  pages:['household/recipes/sourdough.md'], mount:'kanuck' },
  { id:'src_6677aa', title:'K8s 1.29 release notes',          type:'web',      origin:'kubernetes.io',       ingested:'2026-04-10 10:55', ravn:'ratatoskr', pages:['technical/kubernetes/cluster-upgrade.md'], mount:'shared' },
  { id:'src_4092ab', title:'Drive-loop design doc',           type:'document', origin:'niuu/design/drive_loop.md', ingested:'2026-04-14 16:41', ravn:'fjolnir', pages:['projects/niuu/agents/raven.md','entities/concept-drive-loop.md'], mount:'local' },
  { id:'src_c09ee1', title:'UniFi export — Kanuck VLANs',     type:'document', origin:'unifi.kanuck.local',  ingested:'2026-04-15 08:50', ravn:'eir',  pages:['kanuck/infra/homelab.md'], mount:'kanuck' },
  { id:'src_abc123', title:'Tesla AI Day 2021 — transcript',  type:'document', origin:'youtube.com',         ingested:'2026-03-04 14:12', ravn:'ratatoskr', pages:['entities/person-karpathy.md'], mount:'shared' },
  { id:'src_def456', title:'Karpathy OpenAI bio (archive)',   type:'web',      origin:'openai.com/blog',     ingested:'2026-03-04 14:14', ravn:'ratatoskr', pages:['entities/person-karpathy.md'], mount:'shared' },
];

const EVENTS = [
  { t:'10:14:02', kind:'write', mount:'local',  ravn:'fjolnir',  msg:'rewrote compiled-truth of entities/person-karpathy.md', page:'entities/person-karpathy.md' },
  { t:'10:12:40', kind:'lint',  mount:'shared', ravn:'vor',  msg:'auto-fixed L11 (stale index.md, 3 entries added)', page:'index.md' },
  { t:'10:10:18', kind:'ingest',mount:'local',  ravn:'ratatoskr', msg:'ingested src_9a7c22 — karpathy.github.io (pages_updated=1)', page:'entities/person-karpathy.md' },
  { t:'10:08:54', kind:'write', mount:'shared', ravn:'saga',  msg:'appended timeline entry to entities/project-niuu.md', page:'entities/project-niuu.md' },
  { t:'09:54:22', kind:'dream', mount:'kanuck', ravn:'eir',  msg:'dream cycle complete (pages_updated=2, lint_fixes=1)', page:null },
  { t:'09:44:01', kind:'query', mount:'shared', ravn:'fjolnir',  msg:'mimir_query "compounding knowledge" → 4 results', page:null },
  { t:'09:41:12', kind:'ingest',mount:'forge',  ravn:'sindri', msg:'ingested src_f01c22 — Anycubic resin datasheet', page:'technical/forge/resin-profiles.md' },
  { t:'09:22:10', kind:'lint',  mount:'forge',  ravn:'vor',  msg:'L02 contradiction detected in resin-profiles (escalated)', page:'technical/forge/resin-profiles.md' },
  { t:'09:11:08', kind:'write', mount:'local',  ravn:'fjolnir',  msg:'wrote projects/niuu/architecture.md', page:'projects/niuu/architecture.md' },
  { t:'08:58:44', kind:'query', mount:'local',  ravn:'tyr',    msg:'mimir_query (from Týr saga) "cluster upgrade" → 2 results', page:null },
];

// ─── Tree of pages (virtualised for rendering) ────────────────────

function buildTree(pages) {
  const root = { name:'/', children:{}, pages: [] };
  for (const p of pages) {
    const parts = p.path.split('/');
    let node = root;
    for (let i=0; i<parts.length-1; i++) {
      node.children[parts[i]] = node.children[parts[i]] || { name: parts[i], children:{}, pages:[] };
      node = node.children[parts[i]];
    }
    node.pages.push(p);
  }
  return root;
}

// ─── Shared helpers ──────────────────────────────────────────────

const CONF_COLOR = { high:'emerald', medium:'brand', low:'red' };
const STATE_COLOR = {
  healthy:'emerald', working:'emerald', thinking:'brand', observing:'cyan',
  coordinating:'brand', deciding:'purple', degraded:'orange', failed:'red',
  idle:'muted', offline:'muted',
};

window.MIMIR_DATA = {
  MOUNTS, ROUTING_RULES, ROUTING_DEFAULT, RAVNS, PAGES, LINT_CHECKS, LINT_ISSUES,
  SOURCES, EVENTS, buildTree, CONF_COLOR, STATE_COLOR,
};
