ALTER TABLE sagas ADD COLUMN IF NOT EXISTS repo TEXT NOT NULL DEFAULT '';
UPDATE sagas SET repo = repos[1] WHERE array_length(repos, 1) > 0;
ALTER TABLE sagas DROP COLUMN IF EXISTS repos;
ALTER TABLE sagas DROP COLUMN IF EXISTS name;
ALTER TABLE sagas DROP COLUMN IF EXISTS status;
