{{- if and (not .Values.database.existingSecret) .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "volundr.databaseSecretName" . }}
  labels:
    {{- include "volundr.labels" . | nindent 4 }}
  {{- with .Values.database.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.database.username }}
  username: {{ .Values.database.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
stringData:
  {{- with .Values.database.extraSecretData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
