{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "volundr.web.fullname" . }}
  labels:
    {{- include "volundr.web.labels" . | nindent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  {{- if .Values.web.ingress.tls }}
  tls:
    {{- toYaml .Values.web.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "volundr.web.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
