apiVersion: v2
name: tyr
description: "Tyr — saga coordinator (placeholder)"
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Niuu Labs
    url: https://github.com/niuulabs
home: https://github.com/niuulabs/volundr
sources:
  - https://github.com/niuulabs/volundr
