{{- if .Values.codeServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skuld.fullname" . }}-vscode-settings
  labels:
    {{- include "skuld.labels" . | nindent 4 }}
data:
  settings.json: |
{{ .Values.codeServer.settings | toPrettyJson | indent 4 }}
{{- end }}
