#!/usr/bin/env bash
# Spin up a local 3-node Ravn mesh for development and testing.
#
# Each node runs ravn daemon with:
#   - nng mesh transport (Pi mode, no broker)
#   - Static file-based discovery (cluster.yaml, no mDNS)
#   - Separate SQLite memory databases
#   - Unique ports to avoid conflicts
#
# Usage:
#   scripts/ravn-mesh.sh start   — start 3 nodes in background
#   scripts/ravn-mesh.sh stop    — stop all 3 nodes
#   scripts/ravn-mesh.sh status  — show running nodes
#   scripts/ravn-mesh.sh logs    — tail all logs
#   scripts/ravn-mesh.sh peers   — list verified flock members on node 1
#
# Port layout:
#   Node 1: pub=ipc node-1.ipc  rep=ipc node-1-rep.ipc
#   Node 2: pub=ipc node-2.ipc  rep=ipc node-2-rep.ipc
#   Node 3: pub=ipc node-3.ipc  rep=ipc node-3-rep.ipc

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

PIDS_FILE="/tmp/ravn-mesh.pids"
LOG_DIR="/tmp/ravn-mesh"
CONFIG_DIR="/tmp/ravn-mesh"
MEMORY_DIR="/tmp/ravn-mesh"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ravn_cmd() {
    # Run ravn with PYTHONPATH set to src directory
    uv run --project "${REPO_ROOT}" python -m ravn "$@"
}

_write_cluster_yaml() {
    local cluster_path="${CONFIG_DIR}/cluster.yaml"
    cat > "${cluster_path}" <<YAML
# Static peer definitions for local mesh (auto-generated by ravn-mesh.sh)
peers:
  - peer_id: ravn-mesh-1
    persona: coder
    display_name: Kvasir
    pub_address: "ipc:///tmp/ravn-mesh/node-1.ipc"
    rep_address: "ipc:///tmp/ravn-mesh/node-1-rep.ipc"
  - peer_id: ravn-mesh-2
    persona: reviewer
    display_name: Bragi
    pub_address: "ipc:///tmp/ravn-mesh/node-2.ipc"
    rep_address: "ipc:///tmp/ravn-mesh/node-2-rep.ipc"
  - peer_id: ravn-mesh-3
    persona: security
    display_name: Heimdall
    pub_address: "ipc:///tmp/ravn-mesh/node-3.ipc"
    rep_address: "ipc:///tmp/ravn-mesh/node-3-rep.ipc"
YAML
    echo "${cluster_path}"
}

_write_config() {
    local n="$1"          # node number (1, 2, 3)
    local pub_port="$2"
    local rep_port="$3"
    local hs_port="$4"   # unused now, kept for call-site compat
    local persona="$5"
    local display_name="$6"
    local config_path="${CONFIG_DIR}/ravn-mesh-${n}.yaml"

    mkdir -p "${CONFIG_DIR}"

    cat > "${config_path}" <<YAML
# Ravn mesh node ${n} (${persona}) — local dev config (auto-generated by ravn-mesh.sh)

mesh:
  enabled: true
  adapter: nng
  own_peer_id: ravn-mesh-${n}
  nng:
    pub_sub_address: "ipc:///tmp/ravn-mesh/node-${n}.ipc"
    req_rep_address: "ipc:///tmp/ravn-mesh/node-${n}-rep.ipc"

llm:
  model: Qwen/Qwen3-Coder-30B-A3B-Instruct
  max_tokens: 8192
  timeout: 300.0
  provider:
    adapter: ravn.adapters.llm.openai.OpenAICompatibleAdapter
    kwargs:
      base_url: "https://vllm.valaskjalf.asgard.niuu.world"
      api_key: ""
      system_prefix: "You are Ravn, an autonomous agent."

discovery:
  enabled: true
  adapters:
    - adapter: ravn.adapters.discovery.static.StaticDiscoveryAdapter
      cluster_file: "${CONFIG_DIR}/cluster.yaml"
      poll_interval_s: 10

cascade:
  enabled: true

initiative:
  enabled: true
  max_concurrent_tasks: 3
  queue_journal_path: "${MEMORY_DIR}/ravn-mesh-${n}-queue.json"

memory:
  backend: sqlite
  sqlite:
    path: "${MEMORY_DIR}/ravn-mesh-${n}.db"
  reflection_model: Qwen/Qwen3-Coder-30B-A3B-Instruct

mimir:
  enabled: true
  path: ~/.ravn/mimir
  instances:
    - name: local
      role: local
      path: ~/.ravn/mimir
      read_priority: 0
    - name: shared
      role: shared
      url: "https://volundr.valhalla.asgard.niuu.world"
      read_priority: 1

# Allow file tools to access /tmp for demos
permission:
  workspace_root: /tmp

# Skuld channel for browser delivery (mesh cascade visualization)
skuld:
  enabled: true
  broker_url: "ws://localhost:8081/ws/ravn"
  display_name: "${display_name}"

logging:
  level: DEBUG
YAML

    echo "${config_path}"
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

cmd_start() {
    # Kill any leftover processes from a previous run
    local stray_pids
    stray_pids=$(pgrep -f "ravn.*daemon.*ravn-mesh" 2>/dev/null || true)
    if [[ -n "${stray_pids}" ]]; then
        echo "Cleaning up stale ravn-mesh processes..."
        echo "${stray_pids}" | xargs kill -9 2>/dev/null || true
        sleep 1
    fi
    rm -f "${PIDS_FILE}"

    mkdir -p "${LOG_DIR}" "${MEMORY_DIR}"

    echo "Starting Ravn mesh (3 nodes, static discovery)..."
    echo ""

    # Generate cluster.yaml with all peer definitions
    local cluster_file
    cluster_file="$(_write_cluster_yaml)"
    echo "  Cluster file: ${cluster_file}"

    # Node roles (feedback loop demo):
    #   1 — coder     (consumes review.completed, produces code.changed)
    #   2 — reviewer  (consumes code.changed, produces review.completed)
    #   3 — security  (consumes review.completed, produces security.completed)
    # Flow: code.changed → reviewer → review.completed → coder + security
    declare -a configs
    configs[1]="$(_write_config 1 7480 7481 7490 coder Kvasir)"
    configs[2]="$(_write_config 2 7482 7483 7491 reviewer Bragi)"
    configs[3]="$(_write_config 3 7484 7485 7492 security Heimdall)"

    declare -a pids
    local personas=('' coder reviewer security)
    for n in 1 2 3; do
        local log="${LOG_DIR}/ravn-mesh-${n}.log"
        echo "  Node ${n} [${personas[$n]}]: config=${configs[$n]}"
        echo "           log=${log}"

        RAVN_CONFIG="${configs[$n]}" \
            _ravn_cmd daemon --persona "${personas[$n]}" \
            > "${log}" 2>&1 &
        pids[$n]=$!
        echo "           pid=${pids[$n]}"

        # Stagger starts so registry has time to populate
        sleep 2
    done

    # Write all PIDs to file for later cleanup
    printf '%s\n' "${pids[1]}" "${pids[2]}" "${pids[3]}" > "${PIDS_FILE}"

    echo ""
    echo "Mesh started. Nodes will discover each other via mDNS."
    echo ""
    echo "  scripts/ravn-mesh.sh status  — check health"
    echo "  scripts/ravn-mesh.sh logs    — tail all logs"
    echo "  scripts/ravn-mesh.sh peers   — list discovered peers (node 1)"
    echo "  scripts/ravn-mesh.sh stop    — shut everything down"
}

cmd_stop() {
    # Always kill any stray ravn-mesh processes, even if PID file is missing
    local stray_pids
    stray_pids=$(pgrep -f "ravn.*daemon.*ravn-mesh" 2>/dev/null || true)

    if [[ -f "${PIDS_FILE}" ]]; then
        echo "Stopping Ravn mesh..."
        while IFS= read -r pid; do
            if kill -0 "${pid}" 2>/dev/null; then
                kill "${pid}"
                echo "  sent SIGTERM to pid ${pid}"
            else
                echo "  pid ${pid} already gone"
            fi
        done < "${PIDS_FILE}"
        rm -f "${PIDS_FILE}"
    fi

    # Also kill any strays not in the PID file (e.g. from a crashed stop)
    if [[ -n "${stray_pids}" ]]; then
        echo "  killing stray ravn-mesh processes..."
        echo "${stray_pids}" | xargs kill 2>/dev/null || true
    fi

    # Wait briefly then force-kill survivors
    sleep 1
    local survivors
    survivors=$(pgrep -f "ravn.*daemon.*ravn-mesh" 2>/dev/null || true)
    if [[ -n "${survivors}" ]]; then
        echo "  force-killing survivors..."
        echo "${survivors}" | xargs kill -9 2>/dev/null || true
    fi

    echo "Done."
}

cmd_status() {
    if [[ ! -f "${PIDS_FILE}" ]]; then
        echo "No mesh running."
        return
    fi

    echo "Ravn mesh nodes:"
    local n=1
    while IFS= read -r pid; do
        if kill -0 "${pid}" 2>/dev/null; then
            echo "  Node ${n}: pid=${pid}  [running]"
        else
            echo "  Node ${n}: pid=${pid}  [DEAD]"
        fi
        n=$((n + 1))
    done < "${PIDS_FILE}"
}

cmd_logs() {
    local logs=()
    for n in 1 2 3; do
        local log="${LOG_DIR}/ravn-mesh-${n}.log"
        [[ -f "${log}" ]] && logs+=("${log}")
    done

    if [[ ${#logs[@]} -eq 0 ]]; then
        echo "No log files found in ${LOG_DIR}." >&2
        exit 1
    fi

    tail -f "${logs[@]}"
}

cmd_peers() {
    RAVN_CONFIG="${CONFIG_DIR}/ravn-mesh-1.yaml" \
        _ravn_cmd peers --verbose
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

case "${1:-help}" in
    start)  cmd_start ;;
    stop)   cmd_stop ;;
    status) cmd_status ;;
    logs)   cmd_logs ;;
    peers)  cmd_peers ;;
    *)
        echo "Usage: $0 {start|stop|status|logs|peers}"
        exit 1
        ;;
esac
