#!/usr/bin/env bash
# Spin up a local 3-node Ravn mesh for development and testing.
#
# Each node runs ravn daemon with:
#   - nng mesh transport (Pi mode, no broker)
#   - mDNS peer discovery (zeroconf, same host)
#   - Shared ~/.ravn/realm.key for HMAC handshakes
#   - Separate SQLite memory databases
#   - Unique ports to avoid conflicts
#
# Usage:
#   scripts/ravn-mesh.sh start   — start 3 nodes in background
#   scripts/ravn-mesh.sh stop    — stop all 3 nodes
#   scripts/ravn-mesh.sh status  — show running nodes
#   scripts/ravn-mesh.sh logs    — tail all logs
#   scripts/ravn-mesh.sh peers   — list verified flock members on node 1
#
# Port layout:
#   Node 1: pub=7480  rep=7481  handshake=7490
#   Node 2: pub=7482  rep=7483  handshake=7491
#   Node 3: pub=7484  rep=7485  handshake=7492

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

PIDS_FILE="/tmp/ravn-mesh.pids"
LOG_DIR="/tmp/ravn-mesh"
CONFIG_DIR="/tmp/ravn-mesh"
MEMORY_DIR="/tmp/ravn-mesh"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ravn_cmd() {
    # Run ravn with PYTHONPATH set to src directory
    PYTHONPATH="${REPO_ROOT}/src" python -m ravn "$@"
}

_write_config() {
    local n="$1"          # node number (1, 2, 3)
    local pub_port="$2"
    local rep_port="$3"
    local hs_port="$4"
    local persona="$5"
    local config_path="${CONFIG_DIR}/ravn-mesh-${n}.yaml"

    mkdir -p "${CONFIG_DIR}"

    cat > "${config_path}" <<YAML
# Ravn mesh node ${n} (${persona}) — local dev config (auto-generated by ravn-mesh.sh)

mesh:
  enabled: true
  adapter: nng
  own_peer_id: ravn-mesh-${n}
  nng:
    pub_sub_address: "ipc:///tmp/ravn-mesh/node-${n}.ipc"
    req_rep_address: "ipc:///tmp/ravn-mesh/node-${n}-rep.ipc"

llm:
  model: Qwen/Qwen3-Coder-30B-A3B-Instruct
  max_tokens: 8192
  timeout: 300.0
  provider:
    adapter: ravn.adapters.llm.openai.OpenAICompatibleAdapter
    kwargs:
      base_url: "https://vllm.valaskjalf.asgard.niuu.world"
      api_key: ""
      system_prefix: "You are Ravn, an autonomous agent."

discovery:
  enabled: true
  adapter: mdns
  mdns:
    handshake_port: ${hs_port}

cascade:
  enabled: true

initiative:
  enabled: true
  max_concurrent_tasks: 3
  queue_journal_path: "${MEMORY_DIR}/ravn-mesh-${n}-queue.json"

memory:
  backend: sqlite
  sqlite:
    path: "${MEMORY_DIR}/ravn-mesh-${n}.db"
  reflection_model: Qwen/Qwen3-Coder-30B-A3B-Instruct

mimir:
  enabled: true
  path: ~/.ravn/mimir
  instances:
    - name: local
      role: local
      path: ~/.ravn/mimir
      read_priority: 0
    - name: shared
      role: shared
      url: "https://volundr.valhalla.asgard.niuu.world"
      read_priority: 1

# Allow file tools to access /tmp for demos
permission:
  workspace_root: /tmp

persona_source:
  persona_dirs:
    - "${REPO_ROOT}/.ravn/personas"

logging:
  level: DEBUG
YAML

    echo "${config_path}"
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

cmd_start() {
    if [[ -f "${PIDS_FILE}" ]]; then
        echo "Mesh already running? Found ${PIDS_FILE}. Run 'stop' first." >&2
        exit 1
    fi

    mkdir -p "${LOG_DIR}" "${MEMORY_DIR}"

    echo "Starting Ravn mesh (3 nodes)..."
    echo ""

    # Node roles (feedback loop demo):
    #   1 — coder     (consumes review.completed, produces code.changed)
    #   2 — reviewer  (consumes code.changed, produces review.completed)
    #   3 — security  (consumes review.completed, produces security.completed)
    # Flow: code.changed → reviewer → review.completed → coder + security
    declare -a configs
    configs[1]="$(_write_config 1 7480 7481 7490 coder)"
    configs[2]="$(_write_config 2 7482 7483 7491 reviewer)"
    configs[3]="$(_write_config 3 7484 7485 7492 security)"

    declare -a pids
    local personas=('' coder reviewer security)
    for n in 1 2 3; do
        local log="${LOG_DIR}/ravn-mesh-${n}.log"
        echo "  Node ${n} [${personas[$n]}]: config=${configs[$n]}"
        echo "           log=${log}"

        RAVN_CONFIG="${configs[$n]}" \
            _ravn_cmd daemon --persona "${personas[$n]}" \
            > "${log}" 2>&1 &
        pids[$n]=$!
        echo "           pid=${pids[$n]}"

        # Stagger starts so registry has time to populate
        sleep 2
    done

    # Write all PIDs to file for later cleanup
    printf '%s\n' "${pids[1]}" "${pids[2]}" "${pids[3]}" > "${PIDS_FILE}"

    echo ""
    echo "Mesh started. Nodes will discover each other via mDNS."
    echo ""
    echo "  scripts/ravn-mesh.sh status  — check health"
    echo "  scripts/ravn-mesh.sh logs    — tail all logs"
    echo "  scripts/ravn-mesh.sh peers   — list discovered peers (node 1)"
    echo "  scripts/ravn-mesh.sh stop    — shut everything down"
}

cmd_stop() {
    if [[ ! -f "${PIDS_FILE}" ]]; then
        echo "No mesh running (${PIDS_FILE} not found)."
        return
    fi

    echo "Stopping Ravn mesh..."
    while IFS= read -r pid; do
        if kill -0 "${pid}" 2>/dev/null; then
            kill "${pid}"
            echo "  killed pid ${pid}"
        else
            echo "  pid ${pid} already gone"
        fi
    done < "${PIDS_FILE}"

    rm -f "${PIDS_FILE}"
    echo "Done."
}

cmd_status() {
    if [[ ! -f "${PIDS_FILE}" ]]; then
        echo "No mesh running."
        return
    fi

    echo "Ravn mesh nodes:"
    local n=1
    while IFS= read -r pid; do
        if kill -0 "${pid}" 2>/dev/null; then
            echo "  Node ${n}: pid=${pid}  [running]"
        else
            echo "  Node ${n}: pid=${pid}  [DEAD]"
        fi
        n=$((n + 1))
    done < "${PIDS_FILE}"
}

cmd_logs() {
    local logs=()
    for n in 1 2 3; do
        local log="${LOG_DIR}/ravn-mesh-${n}.log"
        [[ -f "${log}" ]] && logs+=("${log}")
    done

    if [[ ${#logs[@]} -eq 0 ]]; then
        echo "No log files found in ${LOG_DIR}." >&2
        exit 1
    fi

    tail -f "${logs[@]}"
}

cmd_peers() {
    RAVN_CONFIG="${CONFIG_DIR}/ravn-mesh-1.yaml" \
        _ravn_cmd peers --verbose
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

case "${1:-help}" in
    start)  cmd_start ;;
    stop)   cmd_stop ;;
    status) cmd_status ;;
    logs)   cmd_logs ;;
    peers)  cmd_peers ;;
    *)
        echo "Usage: $0 {start|stop|status|logs|peers}"
        exit 1
        ;;
esac
