{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "niuu-shared.fullname" . }}
  labels:
    {{- include "niuu-shared.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "niuu-shared.selectorLabels" . | nindent 6 }}
{{- end }}
