apiVersion: v2
name: volundr
description: "Volundr — self-hosted AI-native development platform"
type: application
version: 0.0.0-tyr.159
appVersion: "0.0.0-tyr.159"
keywords:
  - claude
  - code
  - session
  - manager
  - ai
  - kubernetes
maintainers:
  - name: Niuu Labs
    url: https://github.com/niuulabs
home: https://github.com/niuulabs/volundr
sources:
  - https://github.com/niuulabs/volundr
dependencies: []
